### ISSUE TITLE
Roadmap: 0.6.0

### ISSUE THREAD

**Issue by wwwredfish** [Laverna/laverna#54]
1. [ ] Export and print options, to PDF (one note, all notes);
2. [x] MathJax support (issue #53)
3. [x] Multiple databases (issue #47)
4. [x] Working in private mode (issue #46)
5. [x] Android based support (issue #40)
6. [ ] Saving the .md file in clear beside the .json file (issue #9)
